services:
  missav-dlp-web:
    build: .
    container_name: missav-dlp-web
    ports:
      - '55000:5000'
    restart: unless-stopped
    environment:
      - FLASK_HOST=0.0.0.0  # Tells app.py to open to Docker network
    volumes:
      - /home/main/downloads:/app/downloads
      - /home/main/logs:/app/logs

      