services:
  missav-dlp-web:
    build: .
    container_name: missav-dlp-web
    ports:
      - '55000:5000'
    restart: unless-stopped
    volumes:
      # Changed from /downloads to /app/downloads
      - /home/main/downloads:/app/downloads
      # Added this so your task logs don't disappear when container restarts
      - /home/main/logs:/app/logs